server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/service-passenger-user?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        password: nacos
        username: nacos
        enabled: true
  application:
    name: service-passenger-user